sample_rate: 16000
timesteps: 128
repeat: 2
dropout: 0.0
kernel_size_factor: 1.0
labels_full:
- visual
- wow
- learn
- backward
- dog
- two
- left
- happy
- nine
- go
- up
- bed
- stop
- one
- zero
- tree
- seven
- 'on'
- four
- bird
- right
- eight
- 'no'
- six
- forward
- house
- marvin
- sheila
- five
- 'off'
- three
- down
- cat
- follow
- 'yes'
labels_subset:
- 'yes'
- 'no'
- up
- down
- left
- right
- 'on'
- 'off'
- stop
- go
- unknown
- silence
labels:
- visual
- wow
- learn
- backward
- dog
- two
- left
- happy
- nine
- go
- up
- bed
- stop
- one
- zero
- tree
- seven
- 'on'
- four
- bird
- right
- eight
- 'no'
- six
- forward
- house
- marvin
- sheila
- five
- 'off'
- three
- down
- cat
- follow
- 'yes'
train_ds:
  manifest_filepath: null
  sample_rate: 16000
  labels:
  - visual
  - wow
  - learn
  - backward
  - dog
  - two
  - left
  - happy
  - nine
  - go
  - up
  - bed
  - stop
  - one
  - zero
  - tree
  - seven
  - 'on'
  - four
  - bird
  - right
  - eight
  - 'no'
  - six
  - forward
  - house
  - marvin
  - sheila
  - five
  - 'off'
  - three
  - down
  - cat
  - follow
  - 'yes'
  batch_size: 128
  shuffle: true
  is_tarred: false
  tarred_audio_filepaths: null
  tarred_shard_strategy: scatter
  augmentor:
    shift:
      prob: 1.0
      min_shift_ms: -5.0
      max_shift_ms: 5.0
    white_noise:
      prob: 1.0
      min_level: -90
      max_level: -46
validation_ds:
  manifest_filepath: null
  sample_rate: 16000
  labels:
  - visual
  - wow
  - learn
  - backward
  - dog
  - two
  - left
  - happy
  - nine
  - go
  - up
  - bed
  - stop
  - one
  - zero
  - tree
  - seven
  - 'on'
  - four
  - bird
  - right
  - eight
  - 'no'
  - six
  - forward
  - house
  - marvin
  - sheila
  - five
  - 'off'
  - three
  - down
  - cat
  - follow
  - 'yes'
  batch_size: 128
  shuffle: false
  val_loss_idx: 0
test_ds:
  manifest_filepath:
  - /home/smajumdar/PycharmProjects/nemo-eval/nemo_eval/speech_commands/v2_validation_manifest.json
  - /home/smajumdar/PycharmProjects/nemo-eval/nemo_eval/speech_commands/v2_test_manifest.json
  sample_rate: 16000
  labels:
  - visual
  - wow
  - learn
  - backward
  - dog
  - two
  - left
  - happy
  - nine
  - go
  - up
  - bed
  - stop
  - one
  - zero
  - tree
  - seven
  - 'on'
  - four
  - bird
  - right
  - eight
  - 'no'
  - six
  - forward
  - house
  - marvin
  - sheila
  - five
  - 'off'
  - three
  - down
  - cat
  - follow
  - 'yes'
  batch_size: 128
  shuffle: false
  test_loss_idx: 0
  num_workers: 12
  pin_memory: true
preprocessor:
  _target_: nemo.collections.asr.modules.AudioToMFCCPreprocessor
  window_size: 0.025
  window_stride: 0.01
  window: hann
  n_mels: 64
  n_mfcc: 64
  n_fft: 512
spec_augment:
  _target_: nemo.collections.asr.modules.SpectrogramAugmentation
  freq_masks: 2
  time_masks: 2
  freq_width: 15
  time_width: 25
  rect_masks: 5
  rect_time: 25
  rect_freq: 15
crop_or_pad_augment:
  _target_: nemo.collections.asr.modules.CropOrPadSpectrogramAugmentation
  audio_length: 128
encoder:
  _target_: nemo.collections.asr.modules.ConvASREncoder
  feat_in: 64
  activation: relu
  conv_mask: true
  jasper:
  - filters: 128
    repeat: 1
    kernel:
    - 11
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: false
    separable: true
    kernel_size_factor: 1.0
  - filters: 64
    repeat: 2
    kernel:
    - 13
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
    kernel_size_factor: 1.0
  - filters: 64
    repeat: 2
    kernel:
    - 15
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
    kernel_size_factor: 1.0
  - filters: 64
    repeat: 2
    kernel:
    - 17
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
    kernel_size_factor: 1.0
  - filters: 128
    repeat: 1
    kernel:
    - 29
    stride:
    - 1
    dilation:
    - 2
    dropout: 0.0
    residual: false
    separable: true
    kernel_size_factor: 1.0
  - filters: 128
    repeat: 1
    kernel:
    - 1
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: false
decoder:
  _target_: nemo.collections.asr.modules.ConvASRDecoderClassification
  feat_in: 128
  return_logits: true
  pooling_type: avg
  num_classes: 35
optim:
  name: novograd
  lr: 0.05
  betas:
  - 0.95
  - 0.5
  weight_decay: 0.001
  sched:
    name: PolynomialHoldDecayAnnealing
    power: 2.0
    warmup_ratio: 0.05
    hold_ratio: 0.45
    min_lr: 0.001
    last_epoch: -1
target: nemo.collections.asr.models.classification_models.EncDecClassificationModel
nemo_version: 1.19.1
